CREATE TABLE IF NOT EXISTS serialtest (pk SERIAL NOT NULL PRIMARY KEY, intcol INT, strcol VARCHAR(20));
GRANT ALL ON serialtest TO PUBLIC;
CREATE TABLE IF NOT EXISTS uuidtest (pk UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, intcol INT, strcol VARCHAR(20));
GRANT ALL ON uuidtest TO PUBLIC;
CREATE TABLE IF NOT EXISTS compositetest (pk1 INT NOT NULL, pk2 VARCHAR(10) NOT NULL, intcol INT, strcol VARCHAR(20), PRIMARY KEY(pk1, pk2));
GRANT ALL ON compositetest TO PUBLIC;
ALTER USER btest PASSWORD 'btest';
GRANT ALL ON DATABASE batchertestdb TO PUBLIC;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
