project_name: batcher

before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    # - 7

archives:
- wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Update README.md'
      - '^Fix a problem with Postgres connectivity'
      - '^Add Releases link'
      - typo

release:
  github:
    owner: SpokeyWheeler
    name: batcher
  disable: false
  draft: false
  prerelease: auto

nfpms:
  - maintainer: Spokey Wheeler <spokeymon@hotmail.com>
    homepage: https://github.com/SpokeyWheeler/batcher/
    description: batcher does mass database updates and deletes in a database-friendly, concurrent manner
    license: MIT
    formats:
      - deb
      - rpm
      - apk

brews:
  -
    ids:
    - batcher
    name: batcher
    goarm: 6
    github:
      owner: SpokeyWheeler
      name: homebrew-tap
    caveats: "Execute 'batcher help' to get started"
    # license: "MIT"
    description: "batcher does mass database updates and deletes in a database-friendly, concurrent manner"
    test: |
      system "#{bin}/batcher version"

