---
project_name: batcher

archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

brews:
  -
    name: batcher
    tap:
      owner: SpokeyWheeler
      name: homebrew-tap
    caveats: "Execute 'batcher help' to get started"
    # license: "MIT"
    description: "batcher does concurrent mass updates and deletes in a database-friendly way"
    test: |
      system "#{bin}/batcher version"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Update README.md'
      - '^Fix a problem with Postgres connectivity'
      - '^Add Releases link'
      - typo

checksum:
  name_template: 'checksums.txt'

dockers:
  image_templates:
    - spokey/batcher:latest

release:
  github:
    owner: SpokeyWheeler
    name: batcher
  disable: false
  draft: false
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

