project_name: batcher

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64

archives:
- wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Update README.md'
      - '^Fix a problem with Postgres connectivity'
      - '^Add Releases link'
      - typo

release:
  github:
    owner: SpokeyWheeler
    name: batcher
  disable: false
  draft: false
  prerelease: auto

brews:
  -
    name: batcher
    tap:
      owner: SpokeyWheeler
      name: homebrew-tap
    caveats: "Execute 'batcher help' to get started"
    # license: "MIT"
    description: "batcher does mass database updates and deletes in a database-friendly, concurrent manner"
    test: |
      system "#{bin}/batcher version"

