before_install:
  - sudo apt update
  - sudo apt -y upgrade
dist: bionic
go: 1.15.6
language: go
os: linux
jobs:
  include:
    - stage: test
      script: ./build.sh
    - script: test/create_pops.sh
    - script: test/cockroach.sh
    - script: test/mariadb.sh
    - script: test/mysql.sh
    - script: test/postgres.sh
    - stage: release
      script: ./release.sh
      if: branch = main
