before_install:
  - sudo apt update
dist: bionic
go: 1.15.6
language: go
os: linux
jobs:
  include:
    - stage: test
      script: test/cockroach.sh
    - script: test/mariadb.sh
    - stage: release
      script: ./release.sh
      if: branch = main
