# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost:5432/postgres
          PGDATA: /var/lib/postgresql/13/main

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # they don't bloody work though!

    working_directory: /go/src/github.com/SpokeyWheeler/batcher
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: sudo apt update -y
      - run: sudo apt install -y wget
      - run: go get -v -t -d ./...
      - run: go build batcher.go
      - run: wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.3.linux-amd64.tgz | tar xvz
      - run: sudo cp -i cockroach-v20.2.3.linux-amd64/cockroach /usr/local/bin/
      - run: cd test; ./cockroach.sh; cd ..
      - run: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - run: echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" | sudo tee  /etc/apt/sources.list.d/pgdg.list
      - run: sudo apt update -y
      - run: sudo apt install -y postgresql-13
      - run: sudo pg_ctlcluster 13 main start
      # just to check
      - run: sudo pg_ctlcluster 13 main status
      - run: sudo ls -la $PGDATA
      - run: sudo apt install -y postgresql-client-13
      - run: createuser -w -h localhost -d -r -s root
      - run: createuser -w -h localhost -d -r -s btest
      - run: createdb -w -h localhost -O btest batchertestdb
      # just to check
      - run: whoami
      - run: cd test; ./postgres.sh; cd ..
      - run: sudo pg_ctlcluster 13 main stop
