# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost:5432/postgres
          PGDATA: /var/lib/postgresql/11/main

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # they don't bloody work though!

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/SpokeyWheeler/batcher
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y postgresql
      - run: sudo pg_ctlcluster 11 main start
      - run: sudo apt-get install -y postgresql-client
      - run: whoami
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build batcher.go
      - run: createuser -U postgres -h localhost -s root
      - run: cd test; ./test.sh
