# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: cimg/go:1.15
        auth:
          username: $DOCKERUSER
          password: $DOCKERPASS

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

      - image: circleci/postgres:9.6-alpine-ram
        auth:
          username: $DOCKERUSER
          password: $DOCKERPASS
        environment:
          POSTGRES_USER: btest
          POSTGRES_DB: batchertestdb
          TEST_DATABASE_URL: postgresql://btest@localhost:5432/postgres
          PGDATA: /var/lib/postgresql/9.6/main

      - image: circleci/mysql:latest-ram
        auth:
          username: $DOCKERUSER
          password: $DOCKERPASS
        environment:
          MYSQL_ROOT_PASSWORD: btestroot
          MYSQL_DATABASE: batchertestdb
          MYSQL_USER: btest
          MYSQL_PASSWORD: btest

    working_directory: ~/go/src/github.com/SpokeyWheeler/batcher
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: sudo apt update -y
      - run: sudo apt install -y wget postgresql-client mysql-client
      - run: go get -v -t -d ./...
      - run: go build batcher.go
      - run: wget -qO- https://binaries.cockroachdb.com/cockroach-v20.2.3.linux-amd64.tgz | tar xvz
      - run: sudo cp -i cockroach-v20.2.3.linux-amd64/cockroach /usr/local/bin/
      - run: cd test; ./cockroach.sh; cd ..
      - run: cd test; ./postgres.sh; cd ..
      - run: cd test; ./mysql.sh; cd ..
