name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      mariadb:
        image: mariadb
        ports:
          - 4306:4306
        env:
          MYSQL_ROOT_PASSWORD: btestroot
	  MYSQL_DATABASE: batchertestdb
	  MYSQL_USER: btest
	  MYSQL_PASSWORD: btest

      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: btestroot
	  MYSQL_DATABASE: batchertestdb
	  MYSQL_USER: btest
	  MYSQL_PASSWORD: btest

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: btest
          POSTGRES_PASSWORD: btest
          POSTGRES_DB: batchertestdb
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create data load scripts
      run: cd test ; ./create_pops.sh ; cd ..

    - name: Cockroach integration tests
      run: cd test ; ./cockroach.sh ; cd ..

    - name: MariaDB integration tests
      run: cd test ; ./mariadb.sh ; cd ..

    - name: MySQL integration tests
      run: cd test ; ./mysql.sh ; cd ..

    - name: PostgreSQL integration tests
      run: cd test ; ./postgres.sh ; cd ..

